stages:
  - build
  - deploy_artifacts

build:
  stage: build
  image: oven/bun
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - ~/.bun/install/cache/v*
  script:
    - bun install --frozen-lockfile --production
    - bun run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_artifacts:
  stage: deploy_artifacts
  script:
    - echo "Artifacts are stored for further use."
  dependencies:
    - build