stages:
  - build
  - deploy

variables:
  SERVER_USER: "ubuntu"
  SERVER_IP: "84.252.135.61"
  DEPLOY_PATH: "/var/www/frontend"

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: oven/bun:latest
  script:
    - bun install --frozen-lockfile --development
    - bun run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  stage: deploy
  dependencies:
    - build
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$PRIVATE_KEY" > ~/.ssh/private_key.pem
    - chmod 600 ~/.ssh/private_key.pem
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
    - scp -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no -r dist/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
